sonar.projectKey=Chavoloco_qa-backend-code-challenge-betsson
sonar.organization=chavoloco

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=Betsson Online Wallets QA Challenge
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=src
sonar.tests=src/test

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=**/bin/**,**/obj/**,**/.git/**

# C# specific settings
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
